apiVersion: v1
kind: Namespace
metadata:
  name: multilevel-cache-demo
spec: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: multilevel-cache-demo
  namespace: multilevel-cache-demo
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: multilevel-cache-demo
  namespace: multilevel-cache-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: multilevel-cache-demo
  namespace: multilevel-cache-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: multilevel-cache-demo
subjects:
  - kind: ServiceAccount
    name: multilevel-cache-demo
    namespace: multilevel-cache-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multilevel-cache-demo
  name: multilevel-cache-demo
  namespace: multilevel-cache-demo
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: multilevel-cache-demo
  strategy: {}
  template:
    metadata:
      labels:
        app: multilevel-cache-demo
    spec:
      serviceAccountName: multilevel-cache-demo
      containers:
        - image: multilevel-cache-demo:latest
          imagePullPolicy: Never
          name: multilevel-cache-demo
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8888
              protocol: TCP
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx512m -Xms512m -Djava.net.preferIPv4Stack=true"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: multilevel-cache-demo
  name: multilevel-cache-demo
  namespace: multilevel-cache-demo
spec:
  ports:
    - name: 5678-8080
      port: 5678
      protocol: TCP
      targetPort: 8080
  selector:
    app: multilevel-cache-demo
  type: NodePort
